default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: transapp_development

test:
  <<: *default
  database: transapp_test

production:
  <<: *default
  database: transapp_production
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
